[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "maxheap"
version = "0.1.0"
description = "A max-heap library with an API that mirrors Python's heapq (but max-first)."
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"  
authors = [{ name = "Timothy Roch" }]
keywords = ["heap", "priority queue", "max-heap", "data structures"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",  
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Libraries",
  "Typing :: Typed",
]

[project.urls]
Homepage = "https://maxheap.vercel.app"       # update after deployment
Documentation = "https://maxheap.vercel.app/docs"  # update after deployment
Source = "https://github.com/timothyroch/maxheap"
Issues = "https://github.com/timothyroch/maxheap/issues"

[tool.setuptools]
package-dir = {"" = "src"}
license-files = ["LICENSE"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
maxheap = ["py.typed"]

[[tool.setuptools.ext-modules]]
name = "maxheap._cmaxheap"
sources = ["src/maxheap/_cmaxheap.c"]

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]

[tool.ruff]
line-length = 100
target-version = "py39"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B"]
ignore = ["E203"]

[tool.mypy]
python_version = "3.9"
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_optional = true
strict_equality = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
